### ISSUE TITLE
Handling @Context HttpServletRequest

### ISSUE THREAD

**Issue by yissachar** [nmorel/gwt-jackson-rest#5]
Using the Context annotation is common in JAX-RS to retrieve the current HttpServletRequest. This allows for retrieving the current session, amongst other useful things.

Currently it seems that gwt-jackson-rest does not perform any exclusions for Context annotated params. Instead they are generated as part of the API, which causes the code to fail to compile since HttpServletRequest is not available in GWT. 

What should happen instead is that a Context annotated HttpServletRequest param should be excluded from the generated code, since it is not passed in to the API manually, but rather handled automatically by JAX-RS on the server-side.

**Comment by nmorel** [comment]
Hi, 

Could you propose a patch maybe ?
The code to update is around [RestServiceMethod.java#L60](https://github.com/nmorel/gwt-jackson-rest/blob/master/processor/src/main/java/com/github/nmorel/gwtjackson/rest/processor/RestServiceMethod.java#L60) and [GenRestBuilderProcessor.java#L271](https://github.com/nmorel/gwt-jackson-rest/blob/master/processor/src/main/java/com/github/nmorel/gwtjackson/rest/processor/GenRestBuilderProcessor.java#L271).

Otherwise, I'll take a look when I find some time :)

**Comment by yissachar** [comment]
Thanks for the pointers. I've submitted 57628f04d326926d9a295c7d239df50fa4db89ca which fixes the issue.

**Comment by nmorel** [comment]
Thanks for the PR :) It is merged.
